basic.settings:
  type: theme_settings
  label: 'Basic theme settings'
  mapping:
    browser_sync_enabled:
      type: boolean
      label: 'Enable Browser Sync'
    clear_registry:
      type: boolean
      label: 'Enable clear Registry'
    ie_enabled:
      type: boolean
      label: 'Enable IE support HTML classes'
    ie_enabled_versions:
      type: mapping
      label: 'IE versions supported'
      mapping:
        ie8:
          type: boolean
          label: 'Support IE8'
        ie9:
          type: boolean
          label: 'Support IE8'
